### ISSUE TITLE
Recognizing other languages

### ISSUE THREAD

**Issue by niddal-imam** [Sierkinhane/Crnn_Ctpn_Unified#3]
Hi Sierkinhane,

I have tried to use images contain text written in English, but the output were translated into Chinese. Can the model detect other languages?

**Comment by Sierkinhane** [comment]
Sorry for late reply. Exactly yes. You should browse the other repository of mine.

**Comment by Sierkinhane** [comment]
https://github.com/Sierkinhane/crnn_chinese_characters_rec

Just use other training set.
